.\" Manpage for boost_heap.
.TH man 1 "28 Apr 2020" "1.0" "boost_heap man page"
.SH NAME
boost_heap \- example applicationworld 
.SH SYNOPSIS
boost_heap
.SH DESCRIPTION
boost_heap todo ...
.SH OPTIONS
boost_heap todo ...
.SH BUGS
No known bugs.
.SH AUTHOR
@@APPP_AUTHOR@@ @@AUTHOR_EMAIL@@